### ISSUE TITLE
Throws exceptions on hover

### ISSUE THREAD

**Issue by sseppola** [compedit/react-soundcloud-widget#3]
I keep getting an exception whenever I hover the soundcloud element.

![screen shot 2015-03-19 at 2 25 24 pm](https://cloud.githubusercontent.com/assets/4065840/6731288/3c15b9ce-ce44-11e4-9ac6-468c04df06ea.png)

Here's the rendered react element:

return (
      <SoundCloud
          id="react-sc-widget"
          url="https://soundcloud.com/sylvanesso/coffee"
          onPlay={this._onPlay} />
);

Any idea how I can remove it?

**Comment by sseppola** [comment]
Clicking on the share button removes this error somehow

**Comment by compedit** [comment]
I get a few weird errors like that from time to time, hasn't really affected the widget itself though.

You can try removing the share button entirely and see if it helps

```js
return (
  <SoundCloud
    id="react-sc-widget"
    url="https://soundcloud.com/sylvanesso/coffee"
    onPlay={this._onPlay}
    opts={{
      sharing: false
    }}
   />
);

**Comment by sseppola** [comment]
It didn't help. I get these errors all the time, the more I move the cursor the more it prints errors.

**Comment by compedit** [comment]
It looks like they're being thrown from scripts SoundCloud itself loads, there's nothing I can do unfortunately.

**Comment by sseppola** [comment]
Thanks for looking into it
